# Generated by Django 3.0.5 on 2020-04-21 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to=settings.AUTH_USER_MODEL),
        ),
    ]
